name: Python CI with uv

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Gets your code from GitHub

      - name: Install uv
        uses: astral-sh/setup-uv@v5  # Installs uv package manager

      - name: Set up Python
        run: uv python install  # Installs Python version from pyproject.toml or .python-version

      - name: Create Virtual Environment
        run: uv venv .venv  # Creates a virtual environment

      - name: Activate Virtual Environment and Install Dependencies
        run: |
          source .venv/bin/activate  # Activates virtual environment
          uv pip install -r requirements.txt  # Installs dependencies

      - name: Run Python Script
        run: |
          source .venv/bin/activate  # Activates before running script
          python script.py  # Runs script
