jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Check out code

      - name: Install uv
        uses: astral-sh/setup-uv@v5  # Install uv package manager

      - name: Set up Python
        run: uv python install  # Install Python

      - name: Create Virtual Environment
        run: uv venv .venv  # Create a virtual environment

      - name: Activate Virtual Environment and Install Dependencies
        run: |
          source .venv/bin/activate  # Activate virtual environment
          uv pip install -r requirements.txt  # Install dependencies

      - name: Run
